/*
 * REST API
 *
 * Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package rockset

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type QueryLambdaVersion struct {
	// workspace of this Query Lambda
	Workspace string `json:"workspace,omitempty"`
	// user that created this Query Lambda
	CreatedBy string `json:"created_by,omitempty"`
	// ISO-8601 date of when Query Lambda was created
	CreatedAt string `json:"created_at,omitempty"`
	// Query Lambda name
	Name string `json:"name,omitempty"`
	// Query Lambda version
	Version string `json:"version,omitempty"`
	// optional description
	Description string `json:"description,omitempty"`
	// Query Lambda SQL query
	Sql *QueryLambdaSql `json:"sql,omitempty"`
	// collections queried by underlying SQL query
	Collections []string `json:"collections,omitempty"`
	// status of this Query Lambda
	State string `json:"state,omitempty"`
	// stats related to this Query Lambda
	Stats *QueryLambdaStats `json:"stats,omitempty"`
}

func (m QueryLambdaVersion) PrintResponse() {
	r, err := json.Marshal(m)
	var out bytes.Buffer
	err = json.Indent(&out, []byte(string(r)), "", "    ")
	if err != nil {
		fmt.Println("error parsing string")
		return
	}

	fmt.Println(out.String())
}
