/*
REST API

Rockset's REST API allows for creating and managing all resources in Rockset. Each supported endpoint is documented below.  All requests must be authorized with a Rockset API key, which can be created in the [Rockset console](https://console.rockset.com). The API key must be provided as `ApiKey <api_key>` in the `Authorization` request header. For example: ``` Authorization: ApiKey aB35kDjg93J5nsf4GjwMeErAVd832F7ad4vhsW1S02kfZiab42sTsfW5Sxt25asT ```  All endpoints are only accessible via https.  Build something awesome!

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateAliasRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAliasRequest{}

// UpdateAliasRequest struct for UpdateAliasRequest
type UpdateAliasRequest struct {
	// List of fully qualified collection names referenced by alias.
	Collections []string `json:"collections"`
	// Optional description.
	Description *string `json:"description,omitempty"`
}

// NewUpdateAliasRequest instantiates a new UpdateAliasRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAliasRequest(collections []string) *UpdateAliasRequest {
	this := UpdateAliasRequest{}
	this.Collections = collections
	return &this
}

// NewUpdateAliasRequestWithDefaults instantiates a new UpdateAliasRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAliasRequestWithDefaults() *UpdateAliasRequest {
	this := UpdateAliasRequest{}
	return &this
}

// GetCollections returns the Collections field value
func (o *UpdateAliasRequest) GetCollections() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Collections
}

// GetCollectionsOk returns a tuple with the Collections field value
// and a boolean to check if the value has been set.
func (o *UpdateAliasRequest) GetCollectionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Collections, true
}

// SetCollections sets field value
func (o *UpdateAliasRequest) SetCollections(v []string) {
	o.Collections = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateAliasRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAliasRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateAliasRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateAliasRequest) SetDescription(v string) {
	o.Description = &v
}

func (o UpdateAliasRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAliasRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collections"] = o.Collections
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableUpdateAliasRequest struct {
	value *UpdateAliasRequest
	isSet bool
}

func (v NullableUpdateAliasRequest) Get() *UpdateAliasRequest {
	return v.value
}

func (v *NullableUpdateAliasRequest) Set(val *UpdateAliasRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAliasRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAliasRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAliasRequest(val *UpdateAliasRequest) *NullableUpdateAliasRequest {
	return &NullableUpdateAliasRequest{value: val, isSet: true}
}

func (v NullableUpdateAliasRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAliasRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


