version: 2.1
workflows:
  main:
    jobs:
      - test
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: go mod download
      - run: go vet ./...
      - run: go test -v -cover -race -coverprofile=cover.out
      - run: go install github.com/mattn/goveralls@latest
      - run: goveralls -coverprofile=cover.out -service=circle-ci
  release:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: go mod download
      - run:
          name: "Publish Release on GitHub"
          command: |
            curl -sL https://git.io/goreleaser | bash
