// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"github.com/rockset/rockset-go-client/openapi"
	"github.com/rockset/rockset-go-client/option"
	"github.com/rockset/rockset-go-client/paginate"
)

type FakeRockClient struct {
	GetQueryResultsStub        func(context.Context, string, ...option.QueryResultOption) (openapi.QueryPaginationResponse, error)
	getQueryResultsMutex       sync.RWMutex
	getQueryResultsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []option.QueryResultOption
	}
	getQueryResultsReturns struct {
		result1 openapi.QueryPaginationResponse
		result2 error
	}
	getQueryResultsReturnsOnCall map[int]struct {
		result1 openapi.QueryPaginationResponse
		result2 error
	}
	QueryStub        func(context.Context, string, ...option.QueryOption) (openapi.QueryResponse, error)
	queryMutex       sync.RWMutex
	queryArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []option.QueryOption
	}
	queryReturns struct {
		result1 openapi.QueryResponse
		result2 error
	}
	queryReturnsOnCall map[int]struct {
		result1 openapi.QueryResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRockClient) GetQueryResults(arg1 context.Context, arg2 string, arg3 ...option.QueryResultOption) (openapi.QueryPaginationResponse, error) {
	fake.getQueryResultsMutex.Lock()
	ret, specificReturn := fake.getQueryResultsReturnsOnCall[len(fake.getQueryResultsArgsForCall)]
	fake.getQueryResultsArgsForCall = append(fake.getQueryResultsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []option.QueryResultOption
	}{arg1, arg2, arg3})
	stub := fake.GetQueryResultsStub
	fakeReturns := fake.getQueryResultsReturns
	fake.recordInvocation("GetQueryResults", []interface{}{arg1, arg2, arg3})
	fake.getQueryResultsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRockClient) GetQueryResultsCallCount() int {
	fake.getQueryResultsMutex.RLock()
	defer fake.getQueryResultsMutex.RUnlock()
	return len(fake.getQueryResultsArgsForCall)
}

func (fake *FakeRockClient) GetQueryResultsCalls(stub func(context.Context, string, ...option.QueryResultOption) (openapi.QueryPaginationResponse, error)) {
	fake.getQueryResultsMutex.Lock()
	defer fake.getQueryResultsMutex.Unlock()
	fake.GetQueryResultsStub = stub
}

func (fake *FakeRockClient) GetQueryResultsArgsForCall(i int) (context.Context, string, []option.QueryResultOption) {
	fake.getQueryResultsMutex.RLock()
	defer fake.getQueryResultsMutex.RUnlock()
	argsForCall := fake.getQueryResultsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRockClient) GetQueryResultsReturns(result1 openapi.QueryPaginationResponse, result2 error) {
	fake.getQueryResultsMutex.Lock()
	defer fake.getQueryResultsMutex.Unlock()
	fake.GetQueryResultsStub = nil
	fake.getQueryResultsReturns = struct {
		result1 openapi.QueryPaginationResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeRockClient) GetQueryResultsReturnsOnCall(i int, result1 openapi.QueryPaginationResponse, result2 error) {
	fake.getQueryResultsMutex.Lock()
	defer fake.getQueryResultsMutex.Unlock()
	fake.GetQueryResultsStub = nil
	if fake.getQueryResultsReturnsOnCall == nil {
		fake.getQueryResultsReturnsOnCall = make(map[int]struct {
			result1 openapi.QueryPaginationResponse
			result2 error
		})
	}
	fake.getQueryResultsReturnsOnCall[i] = struct {
		result1 openapi.QueryPaginationResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeRockClient) Query(arg1 context.Context, arg2 string, arg3 ...option.QueryOption) (openapi.QueryResponse, error) {
	fake.queryMutex.Lock()
	ret, specificReturn := fake.queryReturnsOnCall[len(fake.queryArgsForCall)]
	fake.queryArgsForCall = append(fake.queryArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []option.QueryOption
	}{arg1, arg2, arg3})
	stub := fake.QueryStub
	fakeReturns := fake.queryReturns
	fake.recordInvocation("Query", []interface{}{arg1, arg2, arg3})
	fake.queryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRockClient) QueryCallCount() int {
	fake.queryMutex.RLock()
	defer fake.queryMutex.RUnlock()
	return len(fake.queryArgsForCall)
}

func (fake *FakeRockClient) QueryCalls(stub func(context.Context, string, ...option.QueryOption) (openapi.QueryResponse, error)) {
	fake.queryMutex.Lock()
	defer fake.queryMutex.Unlock()
	fake.QueryStub = stub
}

func (fake *FakeRockClient) QueryArgsForCall(i int) (context.Context, string, []option.QueryOption) {
	fake.queryMutex.RLock()
	defer fake.queryMutex.RUnlock()
	argsForCall := fake.queryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRockClient) QueryReturns(result1 openapi.QueryResponse, result2 error) {
	fake.queryMutex.Lock()
	defer fake.queryMutex.Unlock()
	fake.QueryStub = nil
	fake.queryReturns = struct {
		result1 openapi.QueryResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeRockClient) QueryReturnsOnCall(i int, result1 openapi.QueryResponse, result2 error) {
	fake.queryMutex.Lock()
	defer fake.queryMutex.Unlock()
	fake.QueryStub = nil
	if fake.queryReturnsOnCall == nil {
		fake.queryReturnsOnCall = make(map[int]struct {
			result1 openapi.QueryResponse
			result2 error
		})
	}
	fake.queryReturnsOnCall[i] = struct {
		result1 openapi.QueryResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeRockClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getQueryResultsMutex.RLock()
	defer fake.getQueryResultsMutex.RUnlock()
	fake.queryMutex.RLock()
	defer fake.queryMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRockClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ paginate.RockClient = new(FakeRockClient)
